### ISSUE TITLE
Sicherheitsempfehlungen

### ISSUE THREAD

**Issue by hupling** [it-at-m/helm-charts#21]
Ich habe einmal Checkmarx Kics über das Helm-Chart AppSwitch-Server laufen gelassen. https://docs.gitlab.com/ee/user/application_security/iac_scanning/ 

Es gibt ein paar Verbesserungsvorschläge für das Helm Chart. 

[gl-sast-report.json](https://github.com/it-at-m/helm-charts/files/15145530/gl-sast-report.json)

@eidottermihi

**Comment by eidottermihi** [comment]
on a first look, I think every issue of the report can be configured by the user of the chart, e.g. container/pod [`securityContext`](https://github.com/it-at-m/helm-charts/blob/main/charts/appswitcher-server/templates/deployment.yaml#L50) and container [`resources`](https://github.com/it-at-m/helm-charts/blob/main/charts/appswitcher-server/templates/deployment.yaml#L100) are freely configurable via values.yaml. 

IMHO thats enough and follows helm standards, as those defaults are configured when creating a new chart via [`helm create`](https://helm.sh/docs/helm/helm_create/#helm-create).
Also changing those defaults in the Chart would be a breaking change for users.
