### ISSUE TITLE
helm repo add on every  chart Readme

### ISSUE THREAD

**Issue by klml** [it-at-m/helm-charts#30]
Currently we have the obligatory `helm repo add it-at-m https://it-at-m.github.io/helm-charts` only on the [main readme](https://github.com/it-at-m/helm-charts/?tab=readme-ov-file#usage), but not on all "sub" charts like [ad2image#installing-the-chart](https://github.com/it-at-m/helm-charts/tree/main/charts/ad2image#installing-the-chart)

This could cause confusion for some users .

I am not sure what todo

* add and repeat `helm repo add it-at-m https://it-at-m.github.io/helm-charts`
* just link to the [main readme](https://github.com/it-at-m/helm-charts/?tab=readme-ov-file#usage)

**Comment by eidottermihi** [comment]
This is covered by ArtifactHub providing further the instructions to first add the repo when clicking on "Install", e.g.

https://artifacthub.io/packages/helm/it-at-m/ad2image

![grafik](https://github.com/it-at-m/helm-charts/assets/2780736/c62826ee-5314-425b-8899-c1e4cc7247d0)

> This could cause confusion for some users .

I would expect that Helm users that want to use Helm charts from public repositories do know that this requires adding the repo ;)
