### ISSUE TITLE
kann auch intern verfügbar sein

### ISSUE THREAD

**Issue by hupling** [it-at-m/helm-charts#41]
Können die Charts auch intern mit Gitlab Pages deployt werden, sodass ich nicht extra einen Proxy setzen muss?

**Comment by eidottermihi** [comment]
Dieses Repo ist für _öffentliche_ Helm Charts von it@M - dementsprechend ist auch nicht vorgesehen, dass diese öffentlichen Charts in einem internen Chart Repository gepublished werden.

**Comment by hupling** [comment]
wenn ich auf meinem PC die Variablen setzten muss, damit es funktioniert, finde ich es nicht schön.
```
    HTTPS_PROXY: 123.123.123.123
    HTTP_PROXY: 123.123.123.123
    NO_PROXY: localhost,muenchen.de
```

Dadurch hat jedes lokale Programm Internetzugriff. 

Gibt es nicht irgendwie besser Zugriffsarten? Oder war das jetzt die beste Zugriffsart und ist mit IT-Security abgesprochen?

**Comment by eidottermihi** [comment]
@hupling diese Diskussion gehört nicht hier her. Mit der Entscheidung, Helm Charts zu unserer Software ebenfalls zu veröffentlichen (dieses Repo, Doku intern: https://git.muenchen.de/ccse/ospo/-/wikis/artifacthub ), folgt daraus auch, dass man für den Zugriff von intern eben entsprechend über den Proxy gehen muss.

Falls hier weiterhin Klärungsbedarf besteht, bitte um Termin (mit @ejcsid ).

**Comment by hupling** [comment]
Vielleicht ist das Thema, ja auch für andere Kommunen interessant, wie unsere Helm Charts in einem internen Netzwerk zur Verfügung gestellt werden können. Daher habe ich kein internes Issue hergenommen, sondern hier öffentlich gefragt.

**Comment by hupling** [comment]
Das Artifactory zu konfigurieren war nicht so einfach. 

https://jfrog.com/help/r/artifactory-how-to-pull-jfrog-charts-using-helm-remote-repository/artifactory-how-to-pull-jfrog-charts-using-helm-remote-repository

Es wird neben einem Remote Repo auch ein Virtuelles Repo benötigt.

Hier noch wie die Urls konfiguriert werden müssen

https://jfrog.com/help/r/artifactory-how-to-configure-the-charts-base-url-in-a-helm-repository/artifactory-how-to-configure-the-charts-base-url-in-a-helm-repository

Jetzt kann zumindest das Refarch-Gateway als Dependency eingebunden werden ohne den Proxy lokal einzurichten. Allerdings funktioniert das ganze nicht mit dem Dave Helm Chart. Dort wird noch auf externe Dependencies postgress und elasticsearch eingebunden. Die Frage ist, ob wir sowas zulassen sollen?
