### ISSUE TITLE
klml is reviewer in every project

### ISSUE THREAD

**Issue by markostreich** [it-at-m/helm-charts#64]
It could become challenging in the future if an administrator is configured as a mandatory reviewer in every project. Currently, this is @klml. Reviews should be mandatory, but the reviewers should be freely selectable.

**Comment by hupling** [comment]
Ist das hier Helm Repo spezifisch? Wenn ich einen MR erstelle, wird bei mir hier der Codeowner https://github.com/it-at-m/helm-charts/blob/main/.github/CODEOWNERS als reviewer eingetragen.

**Comment by klml** [comment]
@markostreich lets change/add @sfi2022 in https://github.com/it-at-m/helm-charts/blob/main/.github/CODEOWNERS#L16
